services:
  backend:
    build:
      context: .
    working_dir: /app
    volumes: 
      - ..:/app
    command: sleep infinity

  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app