services:
  backend:
    build:
      context: .
    working_dir: /app
    volumes: 
      - ..:/app
    command: sleep infinity
    ports:
      - "3000:3000"

  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    volumes:
      - ../database/create.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app